var vars = require('./vars');
var gulp = require('gulp'),

    // GENERAL
    duplicate = require('gulp-rename'),
    gzip = require('gulp-gzip'),
    // filterJs = require('gulp-filter'),

    // DEPLOYMENT
    localServer = require('gulp-connect'),

    // JAVASCRIPT
    concat = require('gulp-concat'),
    uglifyJs = require('gulp-uglify'),
    modernizeJs = require('gulp-modernizr'),
    checkJs = require('gulp-jshint'),
    templateCache = require('gulp-angular-templatecache');

gulp.task('process-scripts', function() {
    return vars.pipeEndProcess(vars.paths.scripts.app, true,
        gulp.src([
            vars.paths.scripts.src + 'app.js',
            vars.paths.scripts.src + 'controllers/index.js',
            vars.paths.scripts.src + 'controllers/*.js',
            vars.paths.scripts.src + 'services/index.js',
            vars.paths.scripts.src + 'services/*.js',
            vars.paths.scripts.src + 'directives/*.js',
            vars.paths.scripts.src + 'filters/*.js',
            // vars.paths.scripts.src + 'autogenerated/*.js',
        ])
        // .pipe(filterJs([vars.ignoredJsFiles]))
        .pipe(concat(vars.renderedJsNames.javascript.myJs))
        .pipe(checkJs())
        .pipe(gulp.dest(vars.paths.scripts.app))
        .pipe(duplicate({
            suffix: '.min'
        }))
        .pipe(uglifyJs())
    );
});

gulp.task('modernizeJs', function() {
    return gulp.src(vars.watchedJsFiles)
        .pipe(modernizeJs())
        .pipe(uglifyJs())
        .pipe(gulp.dest(vars.paths.scripts.src + 'autogenerated/'));
});